volumes:
  db:
# networks:
#   elastic:
#     driver: bridge

services:
  postgres:
    image: postgres:15.8
    container_name: postgres
    environment:
      POSTGRES_DB: md_colab
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5435:5432
    restart: on-failure:3
    volumes:
      - db:/var/lib/postgres/data

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    depends_on:
      - postgres
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:postgres@postgres:5432/md_colab?sslmode=disable
    ports:
      - 8085:8081
    restart: on-failure:3

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    restart: on-failure:3

  backend:
    build: ./server
    container_name: server
    depends_on:
      - postgres
      # - logstash
    environment:
      PG_URL: postgres://postgres:postgres@postgres:5432/md_colab?sslmode=disable
    ports:
      - 3101:3001 # use a different port so local deploy doesn't conflict client dev server
    restart: on-failure:3
    command: bun --watch run ./src/main.ts
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app
          ignore:
            - node_modules
        - action: rebuild
          path: ./server/package.json

  frontend:
    build:
      context: ./client
      target: build
    container_name: client
    depends_on:
      - backend
    ports:
      - 3100:3000 # use a different port so local deploy doesn't conflict client dev server
    restart: on-failure:3
    command: pnpm run dev
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./client/package.json

  httpd:
    build: ./httpd
    container_name: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    restart: on-failure:3
